<?php

return [
    'GET' => [
        '/' => ['PageController', 'home'],
        '/teachers' => ['TeacherController', 'index'],
        '/calendar' => ['PageController', 'pricing'],
        '/pricing' => ['PageController', 'pricing'],
        '/login' => ['AuthController', 'login'],
        '/register' => ['AuthController', 'register'],
        '/forgot-password' => ['AuthController', 'forgotPassword'],
        '/reset-password' => ['AuthController', 'resetPassword'],
        '/email/verify' => ['AuthController', 'verifyNotice'],
        '/logout' => ['AuthController', 'logout'],
        '/dashboard' => ['DashboardController', 'index'],
        '/messages' => ['ChatController', 'index'],
        '/teacher/profile' => ['TeacherController', 'edit'],
        '/teacher/classes' => ['ClassController', 'index'],
        '/admin' => ['AdminController', 'index'],
    ],
    'POST' => [
        '/login' => ['AuthController', 'authenticate'],
        '/register' => ['AuthController', 'store'],
        '/forgot-password' => ['AuthController', 'sendResetLink'],
        '/reset-password' => ['AuthController', 'updatePassword'],
        '/email/verify' => ['AuthController', 'verifyEmail'],
        '/email/resend' => ['AuthController', 'resendVerification'],
        '/logout' => ['AuthController', 'destroy'],
        '/teachers/message' => ['ChatController', 'start'],
        '/messages/send' => ['ChatController', 'send'],
        '/messages/block' => ['ChatController', 'block'],
        '/messages/report' => ['ChatController', 'report'],
        '/classes/request' => ['ClassController', 'requestJoin'],
        '/teacher/profile' => ['TeacherController', 'update'],
        '/teacher/classes' => ['ClassController', 'store'],
        '/teacher/requests/update' => ['ClassController', 'updateRequest'],
        '/admin/admins/create' => ['AdminController', 'createAdmin'],
        '/admin/students/update' => ['AdminController', 'updateStudent'],
        '/admin/educators/update' => ['AdminController', 'updateEducator'],
    ],
];
