<?php

return [
    'GET' => [
        '/' => ['PageController', 'home'],
        '/teachers' => ['TeacherController', 'index'],
        '/lessons' => ['PageController', 'lessons'],
        '/calendar' => ['PageController', 'pricing'],
        '/pricing' => ['PageController', 'pricing'],
        '/privacy' => ['PageController', 'privacy'],
        '/terms' => ['PageController', 'terms'],
        '/login' => ['AuthController', 'login'],
        '/register' => ['AuthController', 'register'],
        '/age-confirmation' => ['AuthController', 'ageConfirmation'],
        '/forgot-password' => ['AuthController', 'forgotPassword'],
        '/reset-password' => ['AuthController', 'resetPassword'],
        '/email/verify' => ['AuthController', 'verifyNotice'],
        '/logout' => ['AuthController', 'logout'],
        '/settings' => ['AuthController', 'settings'],
        '/dashboard' => ['DashboardController', 'index'],
        '/messages' => ['ChatController', 'index'],
        '/teacher/profile' => ['TeacherController', 'edit'],
        '/teacher/classes' => ['ClassController', 'index'],
        '/teacher/classes/edit' => ['ClassController', 'edit'],
        '/admin' => ['AdminController', 'index'],
    ],
    'POST' => [
        '/login' => ['AuthController', 'authenticate'],
        '/register' => ['AuthController', 'store'],
        '/age-confirmation' => ['AuthController', 'confirmAge'],
        '/forgot-password' => ['AuthController', 'sendResetLink'],
        '/reset-password' => ['AuthController', 'updatePassword'],
        '/email/verify' => ['AuthController', 'verifyEmail'],
        '/email/resend' => ['AuthController', 'resendVerification'],
        '/logout' => ['AuthController', 'destroy'],
        '/settings/password' => ['AuthController', 'changePassword'],
        '/teachers/message' => ['ChatController', 'start'],
        '/messages/send' => ['ChatController', 'send'],
        '/messages/block' => ['ChatController', 'block'],
        '/messages/report' => ['ChatController', 'report'],
        '/classes/request' => ['ClassController', 'requestJoin'],
        '/teacher/profile' => ['TeacherController', 'update'],
        '/teacher/classes' => ['ClassController', 'store'],
        '/teacher/classes/update' => ['ClassController', 'update'],
        '/teacher/requests/update' => ['ClassController', 'updateRequest'],
        '/admin/admins/create' => ['AdminController', 'createAdmin'],
        '/admin/settings/update' => ['AdminController', 'updateSettings'],
        '/admin/students/update' => ['AdminController', 'updateStudent'],
        '/admin/educators/update' => ['AdminController', 'updateEducator'],
        '/admin/educators/photos/bulk-update' => ['AdminController', 'bulkUpdateEducatorPhotos'],
        '/admin/lessons/create' => ['AdminController', 'createLessonTopic'],
        '/admin/lessons/bulk-update' => ['AdminController', 'bulkUpdateLessonTopics'],
        '/admin/lessons/update' => ['AdminController', 'updateLessonTopic'],
        '/admin/lessons/delete' => ['AdminController', 'deleteLessonTopic'],
    ],
];
