CREATE TABLE IF NOT EXISTS lesson_topics (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    unit VARCHAR(120) NOT NULL,
    topic VARCHAR(190) NOT NULL UNIQUE,
    image_url VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
